---
specfile_path: hello.spec
synced_files:
- hello.spec
upstream_package_name: hello
downstream_package_name: hello
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64

- job: copr_build
  trigger: release
  metadata:
    targets:
    - fedora-stable
